### ISSUE TITLE
FR: Debug mode

### ISSUE THREAD

**Issue by wanze** [silentzco/statamic-mailchimp#25]
Hi @edalzell 

Thanks for creating this addon! What do you think about introducing a dedicated `debug` mode? If active, the subscriptions are written to the log file and the Mailchimp API is never called. Similar to Statamic's `log` driver for emails.

I could send you a pull request if you think that this feature would be a worthwhile extension.

Cheers

**Comment by edalzell** [comment]
That's a great idea!

**Comment by edalzell** [comment]
@wanze is this something you're still interested in?

**Comment by wanze** [comment]
@edalzell I'm currently not working with Statamic and don't have time to contribute, sorry. But it would be a nice feature for sure! :)

**Comment by edalzell** [comment]
Please re-open if still wanted.
