### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by curtisblackwell** [silentzco/statamic-mailchimp#28]
- [Help article explaining tags](https://mailchimp.com/help/getting-started-tags/)
- [Tags API docs](https://mailchimp.com/developer/guides/how-to-use-tags/)

We'd like to assign tags to contacts who submit our Mailchimp forms. We'll assign a different tag for each form on our site (e.g. footer, contact, blog) to track which forms are effective.

Since we only have one configured form in the addon, we'd like to use our Mailchimp form partial to pass a different value for each place it appears.

---

P.S. Start charging for this addon.

**Comment by edalzell** [comment]
@curtisblackwell to use the API you need to know the `segment` of the tag. How would you go about finding those?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/6069653/73329153-5b307100-4211-11ea-9b22-f17cc127f006.png">

Might need to build a CP thing to retrieve these, which will be much more complicated.

**Comment by curtisblackwell** [comment]
Yeah… I think it'd need to either be retrieved so the user can select it or just input. Could be just in YAML if you didn't wanna build the whole CP side of things.

**Comment by websmyth** [comment]
If we knew the segment ID of a tag, does that make it possible/easier?

**Comment by edalzell** [comment]
This is actually pretty easy to add. @websmyth are your tags per form as well?

**Comment by websmyth** [comment]
Exactly. I’d give the user some options to choose which tag(s) to assign to a form in the CP.

Ideally, it would be great to be able to pull the tags in through the CP – perhaps through a manual ‘refresh’ button – but realise that’s a pain to implement.

**Comment by edalzell** [comment]
- [ ] move repo to `silentzco`
- [ ] rename namespace to `silentz`
- [ ] review config, might do breaking change
- [ ] add config to mailchimp
- [ ] create custom relate/suggest mode to pull tags from mailchimp
- [ ] add selector to config
- [ ] take screenshots of config
- [ ] update docs re tags

**Comment by edalzell** [comment]
in 2.2
