### ISSUE TITLE
2.2.1 update quirks

### ISSUE THREAD

**Issue by websmyth** [silentzco/statamic-mailchimp#44]
A couple of quirks in the install/update:

1. When I updated, Mailchimp became an unlisted addon named Akismet. I removed the previous version and installed from scratch.
2. On `/cp/mailchimp/config/edit` I got `Undefined index: id` , which points at `MailchimpAudience.php` line 31. Setting the Audience ID through the config file fixed this.

**Comment by edalzell** [comment]
> A couple of quirks in the install/update:
> 
> 1. When I updated, Mailchimp became an unlisted addon named Akismet. I removed the previous version and installed from scratch.

@websmyth remove the existing addon then re-add w/ `composer require silentz/mailchimp`. I changed the namespace, I'll update the instructions.

> 2. On `/cp/mailchimp/config/edit` I got `Undefined index: id` , which points at `MailchimpAudience.php` line 31. Setting the Audience ID through the config file fixed this.

Thanks, will fix

**Comment by edalzell** [comment]
fixed in 2.2.2
