### ISSUE TITLE
Server Error on "Save"

### ISSUE THREAD

**Issue by thatdoorsajar** [silentzco/statamic-mailchimp#58]
Hi I'm getting a 500 (Internal Server Error) when I try and click "Save" in the Mailchimp CP Config page. The error has these details in the exception message:

```
Access level to Stillat\\Proteus\\Document\\Printer::hasNodeWithComments() must be protected (as in class PhpParser\\PrettyPrinter\\Standard) or weaker
```

It is connecting to my Mailchimp account in the config page as it lists out all my audiences and tags.

This is on a production server and in local and for both versions `2.4.1` & `2.4.2`

Not sure if others have had this issue previously or if I am doing something wrong!

**Comment by edalzell** [comment]
Can you please run `composer show` and let me know the versions for:

- `edalzell/forma`
- `stillat/proteus`
- `silentz/mailchimp`

**Comment by edalzell** [comment]
nm @thatdoorsajar I can confirm this, it's an issue w/ an underlying package I use.

I'll get it sorted this week.

**Comment by thatdoorsajar** [comment]
Hi @edalzell thanks for confirming underlying issue. Just in case its helpful:

- `edalzell/forma v0.7.2`
- `stillat/proteus v1.0.4`
- `silentz/mailchimp v2.4.2`

**Comment by edalzell** [comment]
> nm @thatdoorsajar I can confirm this, it's an issue w/ an underlying package I use.

For reference: https://github.com/Stillat/proteus/issues/6

**Comment by edalzell** [comment]
This was fixed in Proteus, please update.
