### ISSUE TITLE
Not able to install. Error: $addon must be an instance of Statamic\Extend\Addon

### ISSUE THREAD

**Issue by sandersjj** [silentzco/statamic-mailchimp#59]
I am trying to install this plugin:

`composer require silentz/mailchimp`

But I am not able to do this since I get the following error:

> Typed property Edalzell\Forma\FormaAddon::$addon must be an instance of Statamic\Extend\Addon, null used

- php version 7.4.1
- Statamic 3.0.34

**Comment by edalzell** [comment]
@sandersjj can you please try again on the latest version?

**Comment by sandersjj** [comment]
On the latest version it works.
