### ISSUE TITLE
Error on deploy or when running php please

### ISSUE THREAD

**Issue by philipboomy** [silentzco/statamic-mailchimp#61]
I am getting this on deploy

**In ServiceProvider.php line 12:
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'**  

and it happens after I installed the addon on deploy.

Discovered Addon: [32medalzell/forma[39m
Discovered Addon: [32msilentz/mailchimp[39m

I am using php 7.4

If I tried to php please clear stache for example I get this error as well.

Works locally

**Comment by edalzell** [comment]
Please confirm your prod php version. My bet is that it’s 7.3

**Comment by philipboomy** [comment]
Statamic says: PHP Version | 7.4.12
Forge dashboard says 7.4
Nginx says 7.4

php -v says 7.2 but I think that is just showing what was original installed when server was created.

**Comment by edalzell** [comment]
Well not sure what to tell you, but it's a PHP version issue. The line referenced is using syntax only valid in PHP 7.4.

**Comment by philipboomy** [comment]
Yeah I use using wrong php version on cli. Sorry about that.
