### ISSUE TITLE
Email not in merge fields

### ISSUE THREAD

**Issue by DesignByNeil** [silentzco/statamic-mailchimp#63]
Hi 

I have selected the form, audience and tag but i cant see the email as an option in the merge fields when doing the setup. I can see the other fields available.

Is there anything that would be blocking this?

Thanks

**Comment by edalzell** [comment]
Lets see the merge fields in the audience, in mailchimp, please

**Comment by DesignByNeil** [comment]
Hi Erin

These are the two merge fields. The name field is pulling through but not the email one
![image](https://user-images.githubusercontent.com/51749491/113302146-ae132600-92f7-11eb-8363-4982dfbd06e5.png)


Thanks

**Comment by edalzell** [comment]
Are there any errors in the console?

**Comment by DesignByNeil** [comment]
No errors although i have noticed if i add and then save some settings in the CP that when i go back into the mailchimp addon again that the settings are not there and it is cleared again.

**Comment by edalzell** [comment]
Are the new values saved to the config file?

**Comment by DesignByNeil** [comment]
I have fixed the non saving issue the mailchimp config file was missing but the email field is still not showing up.

```
TypeError
Return value of Silentz\Mailchimp\Subscriber::email() must be of the type string, null returned
```

When you submit the form it is giving the error because the email address is missing.

**Comment by edalzell** [comment]
It's a contact form though right? Why is the email missing? Are you sending it in the form?

**Comment by edalzell** [comment]
> I have fixed the non saving issue the mailchimp config file was missing but the email field is still not showing up.

Ya, nice find, I need to throw an error there or something, thanks for the reminder.

**Comment by DesignByNeil** [comment]
> > I have fixed the non saving issue the mailchimp config file was missing but the email field is still not showing up.
> 
> Ya, nice find, I need to throw an error there or something, thanks for the reminder.

Yeah i hadnt realised that needed created when i added the addon via the cp

**Comment by DesignByNeil** [comment]
> It's a contact form though right? Why is the email missing? Are you sending it in the form?

Ahh ok. I think i have it sorted now. I changed the handle name for the email from `email_address` to `email` and it has submitted. I didnt realise the email address handle had to be email.

Does the email field automatically get added to the merge fields without the need to add them to the forms merge fields in the addon?

Also what does the add users toggle do?

**Comment by edalzell** [comment]
> Ahh ok. I think i have it sorted now. I changed the handle name for the email from `email_address` to `email` and it has submitted. I didnt realise the email address handle had to be email.

It defaults to `email` though you can set the email field name in the `primary_email_field` config.
> 
> Does the email field automatically get added to the merge fields without the need to add them to the forms merge fields in the addon?

No, you have to add in the addon config.

> Also what does the add users toggle do?

It will allow you add user registrations to mailchimp as well. I'm still working on that functionality.

Glad you got it all sorted. Going to close this, if you still have issues let me know.
