### ISSUE TITLE
Can only see 9 audiences in audience Id list

### ISSUE THREAD

**Issue by kristiana-s** [silentzco/statamic-mailchimp#64]
Have added a clients API key, and need to get a specific audience ID, the Mailchimp config page only shows 9 items in the list, where the client has 15, and the one I need is not part of the 9.

Plugins installed:
Statamic v3.1.10
Mailchimp v2.5.5
Aardvark Seo v2.0.10
Duplicator v1.3.0

**Comment by edalzell** [comment]
Nice find @kristiana-s, I can fix this.

**Comment by edalzell** [comment]
hey @kristiana-s can you give the latest release a go?

**Comment by kristiana-s** [comment]
@edalzell yep brill, thats sorted it :) thanks!
