### ISSUE TITLE
Update docs to explain primary_email_field

### ISSUE THREAD

**Issue by francoismajor** [silentzco/statamic-mailchimp#66]
Hi!
I have different forms that use different handles for the email field, and the subscribe wasn't working. I found the `primary_email_field` in the code and defined it in my config and now my forms work. Maybe add that as an option in the docs? (and in the published config file)
```
/*
  * Define the handle for the email field to be used. Defaults to email.
  */
'primary_email_field' => 'email',
```
Thanks!

**Comment by edalzell** [comment]
Thanks for this, updated the readme and the config
