### ISSUE TITLE
Lack of Marketing Permissions

### ISSUE THREAD

**Issue by flythecoopcom** [silentzco/statamic-mailchimp#68]
Hi @edalzell,

Would it be possible to implement functionality to work with Mailchimp's marketing permissions? Although I really like the addon, I'm forced to use a custom implementation using spatie/laravel-newsletter due to the lack of this.

Thanks.

**Comment by edalzell** [comment]
What permissions, do you have a link I could look at?

**Comment by flythecoopcom** [comment]
Of course, below are links to Mailchimp documentation and the implementation by Spatie.
https://mailchimp.com/help/collect-consent-with-gdpr-forms/
https://github.com/spatie/laravel-newsletter#working-with-gdrp-marketing-permissions

**Comment by edalzell** [comment]
And what would you like to be able to do?

**Comment by edalzell** [comment]
Closing due to lack of response.

Please re-open if still relevant.

**Comment by rhoraczek** [comment]
Hi @edalzell,
also for me the possibility to manage the Mailchimp GDPR Marketing Preferences via your addon would be very interesting.
The permission to send marketing material is (unfortunately) essential in the European Union to be able to legally send newsletters. Mailchimp offers under "Settings/GDPR fields and settings" the possibility to define checkboxes and labels , which have to be confirmed in the signup form. Unfortunately, these form fields are not available via the usual merge tags but are rendered in HTML of the standard and embedded signup forms as follows:

`<ul class="interestgroup_field checkbox-group">
<li class="!margin-bottom--lv2">
<label class="checkbox" for="gdpr_199725">
<input type="checkbox" id="gdpr_199725" name="gdpr[199725]" value="Y" }="" class="av-checkbox">
<span>Ja, ich bin mit der Speicherung und Verarbeitung meiner Daten einverstanden und habe die Datenschutzrichtlinien zur Kenntnis genommen.</span>
</label>
</li>
</ul>`

Without this checkbox(es) I could't generate any registrations via your addon so far. Do you have a solution or tip how I can do this with my own Statamic form and your addon?

Thanks, Rudolf

**Comment by edalzell** [comment]
Hi @rhoraczek, I don't really understand sorry.

Can you point me at the Mailchimp documentation about those fields?

**Comment by rhoraczek** [comment]
Hi @edalzell,
here's the link to the documentation of the GDPR fields: https://mailchimp.com/help/collect-consent-with-gdpr-forms/#GDPR_fields

In the last few days I tried some tests on a newsletter signup via your Statamic addon and a standard "embedded signup form" from Mailchimp. Signups via the embedded form all went to Mailchimp without any problems and generated a "thank you" page and the required double opt-in emails to the recipients. Signups via the addon, on the other hand, had no further results (no opt-in emails and no "thank you" page).

Looking at the generated HTML code of my signup form, I noticed two differences.
1. the form tag of the addon looks like this:
<form method="POST" action="https://{myurl}/!/forms/newsletter" id="mc-embedded-subscribe-form" class="form-grid request" target="_blank">.
That of the embedded form like this:
<form action="https://website.us14.list-manage.com/subscribe/post?u=1521790bf364ab7768eb821e8&amp;id={my audience_id}" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="form-grid request" novalidate="">

2. The checkbox I provided for the GDPR field in the Blueprint form looks like this in the addon:
<input type="checkbox" id="GDPR" name="GDPR[]" value="true" aria-required="true" required="">
<label for="GDPR">My GDPR consent text</label>

That of the embedded Mailchimp form, on the other hand, is like this:
<fieldset class="form__field full-width noborder required-field" name="interestgroup_field">
<input type="checkbox" id="gdpr_199725" name="gdpr[199725]" value="Y" aria-required="true" required="">
<label for="gdpr_199725"> My GDPR consent text</label>
</fieldset>

I would be happy if you could tell me what I can do and that my description explains my problem well enough.
Thanks in advance, Rudolf

**Comment by edalzell** [comment]
No images in your comment above, can you please update?

**Comment by rhoraczek** [comment]
Sorry, I thought I had inserted the source.
![form tag of embedded form](https://user-images.githubusercontent.com/40620565/164377689-c05109a5-9adb-4355-82e0-079fab569e98.png)
![form tag of the addon](https://user-images.githubusercontent.com/40620565/164377702-56d88a00-e3e1-4387-a22b-fbb04550cfc1.png)
![GDPR consent text of addon](https://user-images.githubusercontent.com/40620565/164377705-3b0625ac-5508-4b32-af3e-b6120b3e7b82.png)
![GDPR consent text of embedded form](https://user-images.githubusercontent.com/40620565/164377711-0dcee723-e8a6-4c39-b0e0-9416818acf3c.png)

**Comment by edalzell** [comment]
I will take a look at this next week, thanks for your patience

**Comment by edalzell** [comment]
ok @rhoraczek this is not trivial, will get it wrapped up next week.

**Comment by rhoraczek** [comment]
Thank you @edalzell, and sorry for the headache I'm giving you with my request.

**Comment by edalzell** [comment]
ok @flythecoopcom @rhoraczek this is in 2.9, let me know if there are issues.
