### ISSUE TITLE
FR: Add or Update

### ISSUE THREAD

**Issue by kamilahcarter** [silentzco/statamic-mailchimp#71]
Allow the subscribe form to add or update a subscriber in order to cover the cases where someone
- Fills out the form to update their contact info
- Fills out the form to gain access to subscriber only content

Link to discussion in discord: https://discordapp.com/channels/489818810157891584/489862989101662218/940715589205372929

**Comment by edalzell** [comment]
This is a good idea, I'll look at this shortly
