### ISSUE TITLE
UI Issue: Merge fields disappear after saving

### ISSUE THREAD

**Issue by francoismajor** [silentzco/statamic-mailchimp#73]
Hi! I'm having an issue where I can create merge fields using the UI in Statamic, but once I save they disappear.

👉 addon version 2.5.7. Statamic 3.2.32

Create:

![Screen Shot 2022-02-28 at 2 46 10 PM](https://user-images.githubusercontent.com/8515329/156049044-e0f7e23e-2351-4432-89c8-d99b5cd5cdb2.png)

Reload page:

![Screen Shot 2022-02-28 at 2 45 30 PM](https://user-images.githubusercontent.com/8515329/156049084-7cd77915-f54d-43ac-8f03-58d02af11885.png)

The config doesn't change and remains correct. 

![Screen Shot 2022-02-28 at 2 45 35 PM](https://user-images.githubusercontent.com/8515329/156049114-f3901b45-ff00-42e5-acfb-8339b0943fe3.png)

However we can no longer tell if the merge field is the correct one in the UI, or make any changes other than by deleting and adding it again. (ex: for a production site where my client manages their Mailchimp account and wants to add fields).

Thanks!

**Comment by edalzell** [comment]
Thanks for the report, I'll look at it this week.

**Comment by edalzell** [comment]
OK, I've fixed, but  note that config saving doesn't work after Statamic 3.2.32, so I've limited Mailchimp to just that version, for now.
