### ISSUE TITLE
Silentz\Mailchimp\Subscriber::__construct(): Argument #1 ($data) must be of type array

### ISSUE THREAD

**Issue by andrew-ireland** [silentzco/statamic-mailchimp#76]
I'm having trouble getting the 'Mailchimp' addon to work. Form submits fine without it, but I'm seeing this error on submission. Posting in the hope someone smarter than me can point me in the right direction!

I'm running Static v3.3.3

Silentz\Mailchimp\Subscriber::__construct(): Argument #1 ($data) must be of type array, Illuminate\Support\Collection given, called in /Users/andrewireland/www/orion-2022/vendor/silentz/mailchimp/src/Listeners/AddFromSubmission.php on line 12

I've attached my config for reference.

I haven't used Mailchimp or this addon before, so hopefully I'm missing something really obvious. Happy to provide any code as required.

<img width="961" alt="Screen Shot 2022-03-26 at 10 14 36 am" src="https://user-images.githubusercontent.com/18650897/160213618-d626247e-4462-4652-86e0-dde0ec6d34a4.png">

**Comment by edalzell** [comment]
It's due to changes in 3.3, I'll update and push out a release in the next few days.

**Comment by edalzell** [comment]
@andrew-ireland I can't replicate and all my tests still pass.

Can you share a repo that fails?

**Comment by edalzell** [comment]
Closed in 2.7
