### ISSUE TITLE
Statamic control panel, not working with config

### ISSUE THREAD

**Issue by Champs-Callum** [silentzco/statamic-mailchimp#78]
hey guys,

i have added installed the module on my site but the control panel isn't working with tag or merge fields, this is the first time using statamic and also Mailchimp so any help will be much appreciated.

`
<img width="835" alt="Screen Shot 2022-03-28 at 12 52 10" src="https://user-images.githubusercontent.com/97960357/160392840-cc012af4-ac50-4e6b-93a3-a0f1cc4f76b9.png">

**Comment by edalzell** [comment]
What version are you on?

**Comment by Champs-Callum** [comment]
Hi Erin,

Thanks for your email, I am currently running 2.6.1. I have seen that you have released an update so will download that and see if that has fixed my issue.

Many thanks
Callum Jackson

[Text  Description automatically generated with medium confidence]
Because email can be altered electronically, the integrity of this communication cannot be guaranteed. Any views expressed in this email are personal and should not be taken to represent the views of Champions (UK) plc or its associated companies. The information transmitted is confidential and intended only for use to the individual or entity to which it is addressed. If you have received this communication in error, please contact the sender and delete the material from your computer. This email and the information it contains may be privileged and/or confidential. It is for the intended addressee(s) only. The unauthorised use, disclosure or copying of this email, or any information it contains is prohibited and could in certain circumstances be a criminal offence. If you are not the intended recipient, please notify ***@***.******@***.***> immediately and delete the message from your system. Please note that Champions (UK) plc does not enter into any form of contract by means of Internet email. None of the staff at Champions (UK) plc is authorised to enter into contracts on behalf of the company in this way. All contracts to which Champions (UK) plc is a party are documented by other means. Champions (UK) plc monitors emails to ensure its systems operate effectively and to minimise the risk of viruses.  Whilst it has taken reasonable steps to scan this email, it does not accept liability for any virus that it may contain.


From: Erin Dalzell ***@***.***>
Date: Monday, 28 March 2022 at 18:00
To: silentzco/statamic-mailchimp ***@***.***>
Cc: Callum Jackson ***@***.***>, Author ***@***.***>
Subject: Re: [silentzco/statamic-mailchimp] Statamic control panel, not working with config (Issue #78)
CAUTION EXTERNAL EMAIL:
This Message originated outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.
- Helpdesk
________________________________

What version are you on?

**Comment by Champs-Callum** [comment]
Hi Erin, 

i am running the following versions, 
mailchimp module 2.7
statamic 3.3.3

i have attached the errors i am getting in my browser and i am using google chrome
![Screen Shot 2022-03-28 at 15 28 30](https://user-images.githubusercontent.com/97960357/160569361-baab0f2a-3875-4655-a1d6-1813de835551.png)

**Comment by edalzell** [comment]
Any errors in the server log? `laravel.log`?

**Comment by Champs-Callum** [comment]
Hey, I haven't got anything in my laravel.logs file. I now have a connection to Mailchimp. think one of your recent updates has fixed whatever I was having an issue with. I can see the audiences and tags on my Mailchimp settings tab in the CP. but when I submit my form the form submits successfully but the data isn't sent to Mailchimp

**Comment by edalzell** [comment]
By default mail chimp is opt in, so there will be an email that has to be confirmed first, are you seeing that email?

**Comment by edalzell** [comment]
Closing due to lack of response, if this is still an issue please re-open and provide the requested information.
