### ISSUE TITLE
Access level to Edalzell\Mailchimp\ServiceProvider::bootConfig() must be protected or weaker

### ISSUE THREAD

**Issue by benfurfie** [silentzco/statamic-mailchimp#92]
**What is happening?**
When attempting to install the Mailchimp addon via composer running the command `composer require silentz/mailchimp` into a v4 install of Statamic, you get the error:
```
Access level to Edalzell\Mailchimp\ServiceProvider::bootConfig() must be protected (as in class Statamic\Providers\AddonServiceProvider) or weaker
```

This impacts both fresh installs and v2/3 upgrades.

**What should be happening?**
The composer installer should complete without errors.

**Did you RTFM?**
Yes, Erin. I RTFM'd. 😂

**How to reproduce**
1. Run `composer create-project statamic/statamic demo`
2. `cd` into demo
3. Run `composer install` to ensure all default composer packages install correctly.
4. Run `composer require silentz/mailchimp`.
5. See the error during package discovery.

**Environment**
Statamic: 4.1 and Statamic 4.0
PHP: 8.1

**Comment by edalzell** [comment]
Thanks Ben, I'll get a release out this weekend.

**Comment by benfurfie** [comment]
@edalzell – not that I'm aware of. I'll double check with the rest of the team.

**Comment by edalzell** [comment]
Closing in favour of #93
