### ISSUE TITLE
Statamic 4

### ISSUE THREAD

**Issue by duncanmcclean** [silentzco/statamic-mailchimp#93]
We chatted about this on Discord but thought I'd create an issue in case you forget (because I know I do without an issue) about adding Statamic 4 support.

We're planning out Statamic 4 upgrades for our sites at the moment, this addon is a blocker for one of our sites (however, we have no massive rush on our end right now in upgrading)

**Comment by edalzell** [comment]
Hey @robdekort can you try this PR? It's on the `fix/support-v4` branch.

You'd put `dev-fix/support-v4` as the constraint in your `composer.json`.

Note that I took out the GDPR Permissions thing cuz the Spatie package I use doesn't support it any more. I'll add it back in a bit, if this works.

**Comment by robdekort** [comment]
Hey @edalzell. Much appreciated. I'm getting an error about the mailchimp assets missing.

Note: I don't use the GDPR stuff from Mailchimp.

**Comment by robdekort** [comment]
Hmmm the `vendor/silentz/mailchimp/dist` directory is empty.

**Comment by robdekort** [comment]
I was able to compile them.

**Comment by robdekort** [comment]
Ok cool. I was able to subscribe to a mailchimp newsletter via the addon. That seems to work :-).

**Comment by robdekort** [comment]
Neat

**Comment by edalzell** [comment]
@robdekort @duncanmcclean please use 3.0.1, 3.0 was a broken release.

**Comment by robdekort** [comment]
Wonderful Erin. Thanks. Updating the remainder of my sites right now.

**Comment by robdekort** [comment]
Hey Erin,

I'm still running into issues with those darned assets. I don't understand any of that system tbh. Anyways. I'm getting this:

   INFO  Publishing [mailchimp] assets.

   ERROR  Can't locate path: <vendor/silentz/mailchimp/resources/dist/build/>.

**Comment by robdekort** [comment]
I think the `resources/` part shouldn't be in that path.
